version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    command: [
      '--wait_timeout=28800',
      '--max_allowed_packet=32505856'
    ]
    volumes:
      - db_data:/var/lib/mysql
      - ./../:/var/dump/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: toolset
      MYSQL_USER: toolset
      MYSQL_PASSWORD: 1
    ports:
      - '3307:3306'  
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8889:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1
    networks:
      - wpsite
  # Wordpress
  wordpress:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '8888:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: toolset
      WORDPRESS_DB_PASSWORD: 1
      WORDPRESS_DB_NAME: toolset
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: