version: '3'

services:
  web:
    build:
      context: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: "npm run start"
    ports:
      - 3000:3000